### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by fdosani** [ian-whitestone/postgrez#1]
Do you need any help with this? 😄

**Comment by ian-whitestone** [comment]
after actually making the wrapper functions for this project, I now appreciate your decision not to do them for redfox lol. Updates have become a pain in the ass cause you do them in two places.

However, the [one-line wrappers](https://github.com/ian-whitestone/crypto-data/blob/master/main.py#L23) are kinda nice for hacking quick projects
